package main

import (
	"context"
	"fmt"
	"strings"
	"time"

	mmModel "github.com/mattermost/mattermost/server/public/model"

	"github.com/MattermostFederal/mattermost-plugin-crossguard/server/errcode"
	"github.com/MattermostFederal/mattermost-plugin-crossguard/server/store"
	"github.com/MattermostFederal/mattermost-plugin-crossguard/server/wire"
)

type inboundConn struct {
	provider QueueProvider
	name     string
	elector  *inboundElector
}

func (p *Plugin) connectInbound() {
	p.inboundCtx, p.inboundCancel = context.WithCancel(p.ctx)
	ctx := p.inboundCtx

	cfg := p.getConfiguration()
	conns, err := cfg.GetInboundConnections()
	if err != nil {
		p.API.LogError("Failed to parse inbound connections",
			"error_code", errcode.InboundParseConnsFailed,
			"error", err.Error())
		return
	}

	var pool []inboundConn
	for _, conn := range conns {
		provider, err := p.createProvider(conn, "Inbound")
		if err != nil {
			p.API.LogError("Failed to connect inbound",
				"error_code", errcode.InboundConnectFailed,
				"name", conn.Name, "provider", conn.Provider, "error", err.Error())
			continue
		}

		// Subscribe is gated by the cluster-wide single-active-receiver
		// lease. The elector runs in its own goroutine and calls
		// Subscribe / Unsubscribe at the actual leadership transition.
		// File watchers are kept on every node so attachment downloads
		// continue to work regardless of who holds the message lease.
		elector := newInboundElector(p, conn.Name, provider)
		ic := inboundConn{
			provider: provider,
			name:     conn.Name,
			elector:  elector,
		}
		pool = append(pool, ic)

		p.wg.Go(func() {
			elector.run(ctx)
		})

		p.startInboundFileWatchers(ctx, ic)
		p.API.LogInfo("Inbound elector started",
			"error_code", errcode.InboundSubscriptionEstablished,
			"name", conn.Name, "provider", conn.Provider)
	}

	p.inboundMu.Lock()
	p.inboundConns = pool
	p.inboundMu.Unlock()
}

func (p *Plugin) closeInbound() {
	if p.inboundCancel != nil {
		p.inboundCancel()
	}

	p.inboundMu.Lock()
	conns := p.inboundConns
	p.inboundConns = nil
	p.inboundMu.Unlock()

	for _, ic := range conns {
		_ = ic.provider.Close()
	}
}

func (p *Plugin) reconnectInbound() {
	p.closeInbound()
	p.connectInbound()
}

// handleInboundMessage returns a synchronous Subscribe handler. The handler's
// return value is the delivery acknowledgement signal: nil means "processed",
// non-nil means "not processed, redeliver if you can". Each provider's
// Subscribe callback is invoked from a single dispatcher goroutine and
// processes messages serially, so no per-handler concurrency limit is needed.
func (p *Plugin) handleInboundMessage(connName string) func(data []byte) error {
	return func(data []byte) error {
		return p.processInboundMessage(connName, data)
	}
}

func (p *Plugin) processInboundMessage(connName string, data []byte) error {
	p.API.LogDebug("Inbound message received from provider",
		"conn_name", connName, "bytes", len(data))

	env, err := UnmarshalEnvelope(data)
	if err != nil {
		p.API.LogError("Failed to unmarshal transport envelope",
			"error_code", errcode.InboundUnmarshalFailed,
			"conn_name", connName, "error", err.Error())
		// Permanent failure: a malformed message will never succeed on retry.
		return nil
	}

	// Route through the sequencer. For sync_msg envelopes this either
	// dispatches immediately (in-order), buffers (gap), discards
	// (duplicate), or drains a contiguous run of previously-buffered
	// envelopes when the gap fills. Non-sync_msg envelopes pass
	// through unchanged.
	ready := p.sequencer.Admit(connName, env)
	for _, e := range ready {
		if dispatchErr := p.dispatchInboundEnvelope(connName, e); dispatchErr != nil {
			// Returning the error to the provider triggers redelivery on
			// at-least-once transports. Only the first error in a drained
			// batch is reported; subsequent envelopes in the same batch
			// were generated by the same channel state and would face
			// the same transient failure.
			return dispatchErr
		}
	}
	return nil
}

// dispatchInboundEnvelope routes one envelope to the appropriate type
// handler. This is the dispatch layer downstream of the sequencer.
func (p *Plugin) dispatchInboundEnvelope(connName string, env *TransportEnvelope) error {
	switch env.Type {
	case TransportTypeSyncMsg:
		return p.handleInboundSyncMsg(connName, env)
	case TransportTypeTest:
		p.API.LogInfo("Received test message",
			"error_code", errcode.InboundTestReceived,
			"conn_name", connName, "test_id", env.TestID)
		return nil
	case TransportTypeAttachment:
		p.API.LogDebug("Attachment sync not yet implemented",
			"error_code", errcode.InboundAttachmentStubbed,
			"conn_name", connName)
		return nil
	case TransportTypeProfileImage:
		p.API.LogDebug("Profile image sync not yet implemented",
			"error_code", errcode.InboundProfileImageStubbed,
			"conn_name", connName)
		return nil
	default:
		p.API.LogWarn("Unknown transport message type",
			"error_code", errcode.InboundUnknownType,
			"conn_name", connName, "type", env.Type)
		return nil
	}
}

// startSequencerGapTicker drives the per-second sweep that releases
// envelopes whose gap-fill deadline has expired. Released envelopes
// are dispatched the same way as any other ready envelope; the
// sequencer has already audited the lost seq range.
func (p *Plugin) startSequencerGapTicker(ctx context.Context) {
	p.wg.Go(func() {
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case now := <-ticker.C:
				released := p.sequencer.TickGapDeadlines(now)
				for _, env := range released {
					// We do not know which conn delivered the buffered
					// envelope from the sequencer alone. Use env.ConnName
					// which is the envelope's own routing field.
					_ = p.dispatchInboundEnvelope(env.ConnName, env)
				}
			}
		}
	})
}

// sequencerCheckpointInterval is how often the in-memory sequencer
// cursors are flushed to KV. Faster persistence narrows the duplicate-
// redelivery window after leadership handoff but at the cost of more
// KV writes per channel.
const sequencerCheckpointInterval = 5 * time.Second

// startSequencerCheckpointTicker periodically writes the sequencer's
// in-memory cursors to KV so a node taking over the inbound lease can
// reload them and resume without re-dispatching already-processed seqs.
func (p *Plugin) startSequencerCheckpointTicker(ctx context.Context) {
	p.wg.Go(func() {
		ticker := time.NewTicker(sequencerCheckpointInterval)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				p.flushSequencerCheckpoints()
				return
			case <-ticker.C:
				p.flushSequencerCheckpoints()
			}
		}
	})
}

func (p *Plugin) flushSequencerCheckpoints() {
	for _, entry := range p.sequencer.Snapshot() {
		if err := p.kvstore.SetSequencerCursor(entry.ConnName, entry.ChannelID, entry.Epoch, entry.NextExpected); err != nil {
			p.API.LogWarn("Failed to write sequencer cursor checkpoint",
				"error_code", errcode.InboundSeqCheckpointWritten,
				"conn_name", entry.ConnName, "channel_id", entry.ChannelID, "error", err.Error())
			continue
		}
	}
}

func (p *Plugin) handleInboundSyncMsg(connName string, env *TransportEnvelope) error {
	if env.SyncMsg == nil {
		return nil
	}

	// Defense in depth: data arrives from external transport, so reject
	// sync messages targeting a connection that has no inbound subscription
	// configured.
	if !p.hasInboundProvider(connName) {
		p.API.LogWarn("Received sync message for non-inbound connection",
			"error_code", errcode.InboundNotConfigured,
			"conn_name", connName)
		return nil
	}

	team, channel, err := p.resolveTeamAndChannel(connName, env.TeamName, env.ChannelName)
	if err != nil {
		// resolveTeamAndChannel logs and triggers prompts when appropriate;
		// the message is dropped (returning nil) because retrying would not
		// help until an admin links the channel.
		_ = team
		_ = err
		return nil
	}

	conns, kvErr := p.kvstore.GetChannelConnections(channel.Id)
	if kvErr != nil || !hasInboundConnection(conns, connName) {
		p.handleUnlinkedInboundChannel(team, channel, connName)
		return nil
	}

	remoteID := p.remoteIDs["inbound:"+connName]
	if remoteID == "" {
		p.API.LogError("No registered remote for inbound connection",
			"error_code", errcode.InboundNoRemoteForConn,
			"conn_name", connName)
		return nil
	}

	rewriteChannelIDs(env.SyncMsg, channel.Id)

	syncMsg := env.SyncMsg.ToModel()
	resp, err := p.API.ReceiveSharedChannelSyncMsg(remoteID, syncMsg)
	if err != nil {
		p.API.LogError("Failed to receive sync message",
			"error_code", errcode.InboundReceiveSyncFailed,
			"conn_name", connName, "channel_id", channel.Id, "error", err.Error())
		return fmt.Errorf("ReceiveSharedChannelSyncMsg failed: %w", err)
	}

	hasPost := env.SyncMsg != nil && env.SyncMsg.Post != nil
	p.API.LogDebug("ReceiveSharedChannelSyncMsg accepted",
		"conn_name", connName, "channel_id", channel.Id, "has_post", hasPost)

	if errs := joinSyncErrors(resp); errs != "" {
		p.API.LogWarn("Some entities failed to sync",
			"error_code", errcode.InboundPostSyncErrors,
			"conn_name", connName, "errors", errs)
	}
	return nil
}

func joinSyncErrors(resp mmModel.SyncResponse) string {
	var all []string
	all = append(all, resp.UserErrors...)
	all = append(all, resp.PostErrors...)
	all = append(all, resp.ReactionErrors...)
	all = append(all, resp.AcknowledgementErrors...)
	all = append(all, resp.StatusErrors...)
	all = append(all, resp.MembershipErrors...)
	return strings.Join(all, ", ")
}

// rewriteChannelIDs updates ChannelId references in nested SyncMsg entities
// to the local channel ID. The remote sender's view of ChannelId is not
// valid on the receiving side; the server's ReceiveSharedChannelSyncMsg
// uses these IDs to route content.
func rewriteChannelIDs(msg *wire.SyncMsg, localChannelID string) {
	msg.ChannelId = localChannelID
	if msg.Post != nil {
		msg.Post.ChannelId = localChannelID
	}
	for _, reaction := range msg.Reactions {
		if reaction != nil {
			reaction.ChannelId = localChannelID
		}
	}
	for _, mc := range msg.MembershipChanges {
		if mc != nil {
			mc.ChannelId = localChannelID
		}
	}
	for _, ack := range msg.Acknowledgements {
		if ack != nil {
			ack.ChannelId = localChannelID
		}
	}
}

// resolveTeamAndChannel looks up the local team and channel by their remote
// names. If the team is unlinked (no team-level inbound prompt accepted),
// triggers the team-level prompt. If the team is found via the rewrite
// index, uses that.
func (p *Plugin) resolveTeamAndChannel(connName, teamName, channelName string) (*mmModel.Team, *mmModel.Channel, error) {
	team, err := p.findTeamByRewrite(connName, teamName)
	if err != nil {
		return nil, nil, err
	}
	if team == nil {
		var appErr *mmModel.AppError
		team, appErr = p.API.GetTeamByName(teamName)
		if appErr != nil {
			// Unknown team. Cannot post a prompt without a team context.
			return nil, nil, fmt.Errorf("team %q not found: %w", teamName, appErr)
		}
	}

	teamConns, kvErr := p.kvstore.GetTeamConnections(team.Id)
	if kvErr != nil {
		return nil, nil, fmt.Errorf("failed to check team connections: %w", kvErr)
	}
	if !hasInboundConnection(teamConns, connName) {
		p.handleUnlinkedInbound(team, connName)
		return nil, nil, fmt.Errorf("inbound connection %q is not linked to team %q", connName, teamName)
	}

	channel, appErr := p.API.GetChannelByName(team.Id, channelName, false)
	if appErr != nil {
		return nil, nil, fmt.Errorf("channel %q not found in team %q: %w", channelName, teamName, appErr)
	}
	return team, channel, nil
}

func (p *Plugin) findTeamByRewrite(connName, remoteTeamName string) (*mmModel.Team, error) {
	localTeamID, err := p.kvstore.GetTeamRewriteIndex(connName, remoteTeamName)
	if err != nil {
		return nil, fmt.Errorf("rewrite index lookup for %s/%s: %w", connName, remoteTeamName, err)
	}
	if localTeamID == "" {
		return nil, nil
	}
	team, appErr := p.API.GetTeam(localTeamID)
	if appErr != nil {
		return nil, fmt.Errorf("rewrite target team %s not found: %w", localTeamID, appErr)
	}
	return team, nil
}

func hasInboundConnection(conns []store.TeamConnection, connName string) bool {
	for _, tc := range conns {
		if tc.Direction == "inbound" && tc.Connection == connName {
			return true
		}
	}
	return false
}
